spring.application.name=job-portal
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=scott
spring.datasource.password=sama

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret=YTHIWwJwxKyaF5URCg4wpkY+eWevjUhRtJyx37rZOoo=

jwt.access-token.expiration=900000

jwt.refresh-token.expiration=604800000
logging.level.org.springframework.security=TRACE