CREATE TABLE USERS (
    USER_ID NUMBER,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),

    CONSTRAINT CHK_USER_ROLE
        CHECK (ROLE IN ('ADMIN', 'COMPANY', 'USER'))
);

CREATE SEQUENCE USERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_USERS
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT USERS_SEQ.NEXTVAL
        INTO :NEW.USER_ID
        FROM DUAL;
    END IF;
END;

--User Profile
CREATE TABLE USER_PROFILES (

    PROFILE_ID NUMBER,
    USER_ID NUMBER NOT NULL,

    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,

    UNIVERSITY VARCHAR2(100),

    GPA NUMBER(3,2),

    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_USER_PROFILES
        PRIMARY KEY (PROFILE_ID),

    CONSTRAINT FK_PROFILE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ACCOUNT_TYPE
        CHECK
        (
            ACCOUNT_TYPE IN
            (
                'STUDENT',
                'FRESH_GRAD',
                'JUNIOR',
                'MID_LEVEL',
                'SENIOR'
            )
        )
);

CREATE SEQUENCE USER_PROFILES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_USER_PROFILES
BEFORE INSERT ON USER_PROFILES
FOR EACH ROW
BEGIN
    IF :NEW.PROFILE_ID IS NULL THEN
        SELECT USER_PROFILES_SEQ.NEXTVAL
        INTO :NEW.PROFILE_ID
        FROM DUAL;
    END IF;
END;

--skills
CREATE TABLE SKILLS (

      SKILL_ID NUMBER,


    SKILL_NAME VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_SKILLS
        PRIMARY KEY (SKILL_ID),



CREATE SEQUENCE SKILLS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_SKILLS
BEFORE INSERT ON SKILLS
FOR EACH ROW
BEGIN
    IF :NEW.SKILL_ID IS NULL THEN
        SELECT SKILLS_SEQ.NEXTVAL
        INTO :NEW.SKILL_ID
        FROM DUAL;
    END IF;
END;

--Experience
CREATE TABLE EXPERIENCES (

    EXPERIENCE_ID NUMBER,

    PROFILE_ID NUMBER NOT NULL,

    JOB_TITLE VARCHAR2(100) NOT NULL,

    COMPANY_NAME VARCHAR2(100) NOT NULL,

    START_DATE DATE NOT NULL,

    END_DATE DATE,

    IS_CURRENT CHAR(1) DEFAULT 'N'
        CHECK (IS_CURRENT IN ('Y','N')),

    CONSTRAINT PK_EXPERIENCES
        PRIMARY KEY (EXPERIENCE_ID),

    CONSTRAINT FK_EXPERIENCES_PROFILE
        FOREIGN KEY (PROFILE_ID)
        REFERENCES USER_PROFILES(PROFILE_ID)
);

CREATE SEQUENCE EXPERIENCES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_EXPERIENCES
BEFORE INSERT ON EXPERIENCES
FOR EACH ROW
BEGIN
    IF :NEW.EXPERIENCE_ID IS NULL THEN
        SELECT EXPERIENCES_SEQ.NEXTVAL
        INTO :NEW.EXPERIENCE_ID
        FROM DUAL;
    END IF;
END;


--companies
CREATE TABLE COMPANIES (

    COMPANY_ID NUMBER,

    USER_ID NUMBER NOT NULL,

    COMPANY_NAME VARCHAR2(100) NOT NULL,

   IS_APPROVED CHAR(1) DEFAULT 'N'
        CHECK (IS_APPROVED IN ('Y','N')),

    CONSTRAINT PK_COMPANIES
        PRIMARY KEY (COMPANY_ID),

    CONSTRAINT FK_COMPANY_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE COMPANIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_COMPANIES
BEFORE INSERT ON COMPANIES
FOR EACH ROW
BEGIN
    IF :NEW.COMPANY_ID IS NULL THEN
        SELECT COMPANIES_SEQ.NEXTVAL
        INTO :NEW.COMPANY_ID
        FROM DUAL;
    END IF;
END;

--Opportunities

CREATE TABLE OPPORTUNITIES (

    OPPORTUNITY_ID NUMBER,

    COMPANY_ID NUMBER NOT NULL,

    TITLE VARCHAR2(100) NOT NULL,

    DESCRIPTION VARCHAR2(1000),

    LOCATION VARCHAR2(100),

    DEADLINE DATE NOT NULL,

    MAX_APPLICANTS NUMBER NOT NULL,

    STATUS VARCHAR2(20) DEFAULT 'OPEN',

    CONSTRAINT PK_OPPORTUNITIES
        PRIMARY KEY (OPPORTUNITY_ID),

    CONSTRAINT FK_OPPORTUNITY_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES COMPANIES(COMPANY_ID),

    CONSTRAINT CHK_OPPORTUNITY_STATUS
        CHECK (STATUS IN ('OPEN','CLOSED'))
);

CREATE SEQUENCE OPPORTUNITIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_OPPORTUNITIES
BEFORE INSERT ON OPPORTUNITIES
FOR EACH ROW
BEGIN
    IF :NEW.OPPORTUNITY_ID IS NULL THEN
        SELECT OPPORTUNITIES_SEQ.NEXTVAL
        INTO :NEW.OPPORTUNITY_ID
        FROM DUAL;
    END IF;
END;

--jobs

CREATE TABLE JOBS (

    OPPORTUNITY_ID NUMBER,

    SALARY NUMBER(10,2),

    WORK_MODE VARCHAR2(20),

    CONSTRAINT PK_JOBS
        PRIMARY KEY (OPPORTUNITY_ID),

    CONSTRAINT FK_JOB_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),

    CONSTRAINT CHK_WORK_MODE
        CHECK (WORK_MODE IN ('ONSITE','HYBRID','REMOTE'))
);

--Internships

CREATE TABLE INTERNSHIPS (

    OPPORTUNITY_ID NUMBER,

    DURATION_MONTHS NUMBER NOT NULL,

    IS_PAID CHAR(1) DEFAULT 'N'
        CHECK (IS_PAID IN ('Y','N')),

    CONSTRAINT PK_INTERNSHIPS
        PRIMARY KEY (OPPORTUNITY_ID),

    CONSTRAINT FK_INTERNSHIP_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID)
);

--User-skill

CREATE TABLE USER_SKILLS (

    PROFILE_ID NUMBER,

    SKILL_ID NUMBER,

    CONSTRAINT PK_USER_SKILLS
        PRIMARY KEY (PROFILE_ID, SKILL_ID),

    CONSTRAINT FK_USER_SKILLS_PROFILE
        FOREIGN KEY (PROFILE_ID)
        REFERENCES USER_PROFILES(PROFILE_ID),

    CONSTRAINT FK_USER_SKILLS_SKILL
        FOREIGN KEY (SKILL_ID)
        REFERENCES SKILLS(SKILL_ID)
);

CREATE TABLE OPPORTUNITY_SKILLS (

    OPPORTUNITY_ID NUMBER,

    SKILL_ID NUMBER,

    CONSTRAINT PK_OPPORTUNITY_SKILLS
        PRIMARY KEY (OPPORTUNITY_ID, SKILL_ID),

    CONSTRAINT FK_OPPORTUNITY_SKILLS_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),

    CONSTRAINT FK_OPPORTUNITY_SKILLS_SKILL
        FOREIGN KEY (SKILL_ID)
        REFERENCES SKILLS(SKILL_ID)
);

--Application
CREATE TABLE APPLICATIONS (

    APPLICATION_ID NUMBER,

    PROFILE_ID NUMBER NOT NULL,

    OPPORTUNITY_ID NUMBER NOT NULL,

    APPLICATION_DATE DATE DEFAULT SYSDATE,

    STATUS VARCHAR2(20) DEFAULT 'PENDING',

    CONSTRAINT PK_APPLICATIONS
        PRIMARY KEY (APPLICATION_ID),

    CONSTRAINT FK_APPLICATION_PROFILE
        FOREIGN KEY (PROFILE_ID)
        REFERENCES USER_PROFILES(PROFILE_ID),

    CONSTRAINT FK_APPLICATION_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),

    CONSTRAINT CHK_APPLICATION_STATUS
        CHECK (STATUS IN ('PENDING','ACCEPTED','REJECTED'))
);

CREATE SEQUENCE APPLICATIONS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_APPLICATIONS
BEFORE INSERT ON APPLICATIONS
FOR EACH ROW
BEGIN
    IF :NEW.APPLICATION_ID IS NULL THEN
        SELECT APPLICATIONS_SEQ.NEXTVAL
        INTO :NEW.APPLICATION_ID
        FROM DUAL;
    END IF;
END;


--Notification
CREATE TABLE NOTIFICATIONS (

    NOTIFICATION_ID NUMBER,

    USER_ID NUMBER NOT NULL,

    MESSAGE VARCHAR2(500) NOT NULL,

    CREATED_AT DATE DEFAULT SYSDATE,

    IS_READ CHAR(1) DEFAULT 'N'
        CHECK (IS_READ IN ('Y','N')),

    CONSTRAINT PK_NOTIFICATIONS
        PRIMARY KEY (NOTIFICATION_ID),

    CONSTRAINT FK_NOTIFICATION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE NOTIFICATIONS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_NOTIFICATIONS
BEFORE INSERT ON NOTIFICATIONS
FOR EACH ROW
BEGIN
    IF :NEW.NOTIFICATION_ID IS NULL THEN
        SELECT NOTIFICATIONS_SEQ.NEXTVAL
        INTO :NEW.NOTIFICATION_ID
        FROM DUAL;
    END IF;
END;

