CREATE TABLE USERS (
    USER_ID NUMBER,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),

    CONSTRAINT CHK_USER_ROLE
        CHECK (ROLE IN ('ADMIN', 'COMPANY', 'USER'))
);

CREATE SEQUENCE USERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


--User Profile
CREATE TABLE USER_PROFILES (

    PROFILE_ID NUMBER,
    USER_ID NUMBER NOT NULL,

    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,

    UNIVERSITY VARCHAR2(100),

    GPA NUMBER(3,2),

    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_USER_PROFILES
        PRIMARY KEY (PROFILE_ID),

    CONSTRAINT FK_PROFILE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ACCOUNT_TYPE
        CHECK
        (
            ACCOUNT_TYPE IN
            (
                'STUDENT',
                'FRESH_GRAD',
                'JUNIOR',
                'MID_LEVEL',
                'SENIOR'
            )
        )
);

CREATE SEQUENCE USER_PROFILES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


--skills
CREATE TABLE SKILLS (

      SKILL_ID NUMBER,


    SKILL_NAME VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_SKILLS
        PRIMARY KEY (SKILL_ID));



CREATE SEQUENCE SKILLS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


--Experience
CREATE TABLE EXPERIENCES (

    EXPERIENCE_ID NUMBER,

    PROFILE_ID NUMBER NOT NULL,

    JOB_TITLE VARCHAR2(100) NOT NULL,

    COMPANY_NAME VARCHAR2(100) NOT NULL,

    START_DATE DATE NOT NULL,

    END_DATE DATE,

    IS_CURRENT CHAR(1) DEFAULT 'N'
        CHECK (IS_CURRENT IN ('Y','N')),

    CONSTRAINT PK_EXPERIENCES
        PRIMARY KEY (EXPERIENCE_ID),

    CONSTRAINT FK_EXPERIENCES_PROFILE
        FOREIGN KEY (PROFILE_ID)
        REFERENCES USER_PROFILES(PROFILE_ID)
);

CREATE SEQUENCE EXPERIENCES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;



--companies
CREATE TABLE COMPANIES (

    COMPANY_ID NUMBER,

    USER_ID NUMBER NOT NULL,

    COMPANY_NAME VARCHAR2(100) NOT NULL,

   IS_APPROVED CHAR(1) DEFAULT 'N'
        CHECK (IS_APPROVED IN ('Y','N')),

    CONSTRAINT PK_COMPANIES
        PRIMARY KEY (COMPANY_ID),

    CONSTRAINT FK_COMPANY_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE COMPANIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


--Opportunities

CREATE TABLE OPPORTUNITIES (

    OPPORTUNITY_ID NUMBER,

    COMPANY_ID NUMBER NOT NULL,

    TITLE VARCHAR2(100) NOT NULL,

    DESCRIPTION VARCHAR2(1000),

    LOCATION VARCHAR2(100),

    DEADLINE DATE NOT NULL,

    MAX_APPLICANTS NUMBER NOT NULL,

    STATUS VARCHAR2(20) DEFAULT 'OPEN',

    CONSTRAINT PK_OPPORTUNITIES
        PRIMARY KEY (OPPORTUNITY_ID),

    CONSTRAINT FK_OPPORTUNITY_COMPANY
        FOREIGN KEY (COMPANY_ID)
        REFERENCES COMPANIES(COMPANY_ID),

    CONSTRAINT CHK_OPPORTUNITY_STATUS
        CHECK (STATUS IN ('OPEN','CLOSED'))
);

CREATE SEQUENCE OPPORTUNITIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


--jobs

CREATE TABLE JOBS (

    OPPORTUNITY_ID NUMBER,

    SALARY NUMBER(10,2),

    WORK_MODE VARCHAR2(20),

    CONSTRAINT PK_JOBS
        PRIMARY KEY (OPPORTUNITY_ID),

    CONSTRAINT FK_JOB_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),

    CONSTRAINT CHK_WORK_MODE
        CHECK (WORK_MODE IN ('ONSITE','HYBRID','REMOTE'))
);

--Internships

CREATE TABLE INTERNSHIPS (

    OPPORTUNITY_ID NUMBER,

    DURATION_MONTHS NUMBER NOT NULL,

    IS_PAID CHAR(1) DEFAULT 'N'
        CHECK (IS_PAID IN ('Y','N')),

    CONSTRAINT PK_INTERNSHIPS
        PRIMARY KEY (OPPORTUNITY_ID),

    CONSTRAINT FK_INTERNSHIP_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID)
);

--User-skill

CREATE TABLE USER_SKILLS (

    PROFILE_ID NUMBER,

    SKILL_ID NUMBER,

    CONSTRAINT PK_USER_SKILLS
        PRIMARY KEY (PROFILE_ID, SKILL_ID),

    CONSTRAINT FK_USER_SKILLS_PROFILE
        FOREIGN KEY (PROFILE_ID)
        REFERENCES USER_PROFILES(PROFILE_ID),

    CONSTRAINT FK_USER_SKILLS_SKILL
        FOREIGN KEY (SKILL_ID)
        REFERENCES SKILLS(SKILL_ID)
);

CREATE TABLE OPPORTUNITY_SKILLS (

    OPPORTUNITY_ID NUMBER,

    SKILL_ID NUMBER,

    CONSTRAINT PK_OPPORTUNITY_SKILLS
        PRIMARY KEY (OPPORTUNITY_ID, SKILL_ID),

    CONSTRAINT FK_OPP_SKILLS_OPP
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),

    CONSTRAINT FK_OPPORTUNITY_SKILLS_SKILL
        FOREIGN KEY (SKILL_ID)
        REFERENCES SKILLS(SKILL_ID)
);

--Application
CREATE TABLE APPLICATIONS (

    APPLICATION_ID NUMBER,

    PROFILE_ID NUMBER NOT NULL,

    OPPORTUNITY_ID NUMBER NOT NULL,

    APPLICATION_DATE DATE DEFAULT SYSDATE,

    STATUS VARCHAR2(20) DEFAULT 'PENDING',

    CONSTRAINT PK_APPLICATIONS
        PRIMARY KEY (APPLICATION_ID),

    CONSTRAINT FK_APPLICATION_PROFILE
        FOREIGN KEY (PROFILE_ID)
        REFERENCES USER_PROFILES(PROFILE_ID),

    CONSTRAINT FK_APPLICATION_OPPORTUNITY
        FOREIGN KEY (OPPORTUNITY_ID)
        REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),

    CONSTRAINT CHK_APPLICATION_STATUS
        CHECK (STATUS IN ('PENDING','ACCEPTED','REJECTED'))
);

CREATE SEQUENCE APPLICATIONS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;



--Notification
CREATE TABLE NOTIFICATIONS (

    NOTIFICATION_ID NUMBER,

    USER_ID NUMBER NOT NULL,

    MESSAGE VARCHAR2(500) NOT NULL,

    CREATED_AT DATE DEFAULT SYSDATE,

    IS_READ CHAR(1) DEFAULT 'N'
        CHECK (IS_READ IN ('Y','N')),

    CONSTRAINT PK_NOTIFICATIONS
        PRIMARY KEY (NOTIFICATION_ID),

    CONSTRAINT FK_NOTIFICATION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE NOTIFICATIONS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

/*=========================================================
    MODIFY USER_SKILLS
=========================================================*/

-- Drop existing composite primary key
ALTER TABLE USER_SKILLS
DROP PRIMARY KEY;

-- Add surrogate primary key
ALTER TABLE USER_SKILLS
ADD USER_SKILL_ID NUMBER;

-- Create sequence
CREATE SEQUENCE USER_SKILLS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



-- Set new primary key
ALTER TABLE USER_SKILLS
ADD CONSTRAINT PK_USER_SKILLS
PRIMARY KEY (USER_SKILL_ID);

-- Prevent duplicate user-skill combinations
ALTER TABLE USER_SKILLS
ADD CONSTRAINT UK_USER_SKILLS
UNIQUE (PROFILE_ID, SKILL_ID);



/*=========================================================
    MODIFY OPPORTUNITY_SKILLS
=========================================================*/

-- Drop existing composite primary key
ALTER TABLE OPPORTUNITY_SKILLS
DROP PRIMARY KEY;

-- Add surrogate primary key
ALTER TABLE OPPORTUNITY_SKILLS
ADD OPPORTUNITY_SKILL_ID NUMBER;

-- Create sequence
CREATE SEQUENCE OPPORTUNITY_SKILLS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


-- Set new primary key
ALTER TABLE OPPORTUNITY_SKILLS
ADD CONSTRAINT PK_OPPORTUNITY_SKILLS
PRIMARY KEY (OPPORTUNITY_SKILL_ID);

-- Prevent duplicate opportunity-skill combinations
ALTER TABLE OPPORTUNITY_SKILLS
ADD CONSTRAINT UK_OPPORTUNITY_SKILLS
UNIQUE (OPPORTUNITY_ID, SKILL_ID);

-- Remove the approval column
ALTER TABLE COMPANIES
DROP COLUMN IS_APPROVED;

-- Add the industry column
ALTER TABLE COMPANIES
ADD INDUSTRY VARCHAR2(100) NOT NULL;